parsers-message-queue: parsers
server-backlog: 1000
server-local-dir: data
server-snapshot-filename: snapshot
message-queue-parsers-tag: parsers

# TODO: remove
message-queue-default-exchange: brainiac
message-queue-default-routing-key: parsers